url: "https://nishantdania.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Nishant Dania" # the name of your site, e.g. ACME Corp.

permalink: /posts/:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
